name: car_rental_system
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  image_cropper: ^2.0.3
  cached_network_image: ^3.2.1
  google_maps_flutter: ^2.1.8
  geolocator: ^8.2.1
  connectivity_plus: ^2.3.5
  firebase_database: ^9.0.16
  dio: ^4.0.6
  flutter_polyline_points: ^1.0.0
  flutter_geofire: ^2.0.1
  razorpay_flutter: ^1.3.0
  toast: ^0.3.0
  table_calendar: ^3.0.6
  freezed: ^2.0.3+1
  path: ^1.8.1
  uuid: ^3.0.6
  image_picker: ^0.8.5+3
  flutter_form_builder: ^7.3.1
  form_builder_validators: ^8.1.1
  page_transition: ^2.0.9
  permission_handler: ^10.0.0
  flutter_easyloading: ^3.0.5
  location: ^4.4.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  lint: ^1.8.2
  freezed_annotation: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - images/
