// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8XbZm1eqMpQbkfjC92xJJeYdBZ_qTnto',
    appId: '1:1016734844278:android:6d6b3569d67502a0536657',
    messagingSenderId: '1016734844278',
    projectId: 'carrentalsystem-ef6ae',
    databaseURL: 'https://carrentalsystem-ef6ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carrentalsystem-ef6ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsvxMOT0-PSClgB4Mk7t6uA7Ij-PhL4UU',
    appId: '1:1016734844278:ios:eff1f253b6db7aa9536657',
    messagingSenderId: '1016734844278',
    projectId: 'carrentalsystem-ef6ae',
    databaseURL: 'https://carrentalsystem-ef6ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carrentalsystem-ef6ae.appspot.com',
    iosClientId: '1016734844278-obgq6ece1b0e8ch1nf62pgi255lpueba.apps.googleusercontent.com',
    iosBundleId: 'com.example.hopon',
  );
}
